# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = J:\Shep

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = J:\Shep

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start J:\Shep\CMakeFiles J:\Shep\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start J:\Shep\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shep

# Build rule for target.
Shep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Shep
.PHONY : Shep

# fast build rule for target.
Shep/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/build
.PHONY : Shep/fast

#=============================================================================
# Target rules for targets named copy_data

# Build rule for target.
copy_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 copy_data
.PHONY : copy_data

# fast build rule for target.
copy_data/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\copy_data.dir\build.make CMakeFiles/copy_data.dir/build
.PHONY : copy_data/fast

src/GameObject.o: src/GameObject.cpp.o
.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i
.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s
.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/ShepGame.o: src/ShepGame.cpp.o
.PHONY : src/ShepGame.o

# target to build an object file
src/ShepGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/ShepGame.cpp.o
.PHONY : src/ShepGame.cpp.o

src/ShepGame.i: src/ShepGame.cpp.i
.PHONY : src/ShepGame.i

# target to preprocess a source file
src/ShepGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/ShepGame.cpp.i
.PHONY : src/ShepGame.cpp.i

src/ShepGame.s: src/ShepGame.cpp.s
.PHONY : src/ShepGame.s

# target to generate assembly for a file
src/ShepGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/ShepGame.cpp.s
.PHONY : src/ShepGame.cpp.s

src/olcPGEX_MiniAudio.o: src/olcPGEX_MiniAudio.cpp.o
.PHONY : src/olcPGEX_MiniAudio.o

# target to build an object file
src/olcPGEX_MiniAudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPGEX_MiniAudio.cpp.o
.PHONY : src/olcPGEX_MiniAudio.cpp.o

src/olcPGEX_MiniAudio.i: src/olcPGEX_MiniAudio.cpp.i
.PHONY : src/olcPGEX_MiniAudio.i

# target to preprocess a source file
src/olcPGEX_MiniAudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPGEX_MiniAudio.cpp.i
.PHONY : src/olcPGEX_MiniAudio.cpp.i

src/olcPGEX_MiniAudio.s: src/olcPGEX_MiniAudio.cpp.s
.PHONY : src/olcPGEX_MiniAudio.s

# target to generate assembly for a file
src/olcPGEX_MiniAudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPGEX_MiniAudio.cpp.s
.PHONY : src/olcPGEX_MiniAudio.cpp.s

src/olcPixelGameEngine.o: src/olcPixelGameEngine.cpp.o
.PHONY : src/olcPixelGameEngine.o

# target to build an object file
src/olcPixelGameEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPixelGameEngine.cpp.o
.PHONY : src/olcPixelGameEngine.cpp.o

src/olcPixelGameEngine.i: src/olcPixelGameEngine.cpp.i
.PHONY : src/olcPixelGameEngine.i

# target to preprocess a source file
src/olcPixelGameEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPixelGameEngine.cpp.i
.PHONY : src/olcPixelGameEngine.cpp.i

src/olcPixelGameEngine.s: src/olcPixelGameEngine.cpp.s
.PHONY : src/olcPixelGameEngine.s

# target to generate assembly for a file
src/olcPixelGameEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/olcPixelGameEngine.cpp.s
.PHONY : src/olcPixelGameEngine.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... copy_data
	@echo ... Shep
	@echo ... src/GameObject.o
	@echo ... src/GameObject.i
	@echo ... src/GameObject.s
	@echo ... src/ShepGame.o
	@echo ... src/ShepGame.i
	@echo ... src/ShepGame.s
	@echo ... src/olcPGEX_MiniAudio.o
	@echo ... src/olcPGEX_MiniAudio.i
	@echo ... src/olcPGEX_MiniAudio.s
	@echo ... src/olcPixelGameEngine.o
	@echo ... src/olcPixelGameEngine.i
	@echo ... src/olcPixelGameEngine.s
	@echo ... src/util.o
	@echo ... src/util.i
	@echo ... src/util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

