# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = J:\Shep

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = J:\Shep

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start J:\Shep\CMakeFiles J:\Shep\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start J:\Shep\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shep

# Build rule for target.
Shep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Shep
.PHONY : Shep

# fast build rule for target.
Shep/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/build
.PHONY : Shep/fast

#=============================================================================
# Target rules for targets named copy_data

# Build rule for target.
copy_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 copy_data
.PHONY : copy_data

# fast build rule for target.
copy_data/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\copy_data.dir\build.make CMakeFiles/copy_data.dir/build
.PHONY : copy_data/fast

CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/main.cpp.s
.PHONY : main.cpp.s

olcPGEX_MiniAudio.o: olcPGEX_MiniAudio.cpp.o
.PHONY : olcPGEX_MiniAudio.o

# target to build an object file
olcPGEX_MiniAudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPGEX_MiniAudio.cpp.o
.PHONY : olcPGEX_MiniAudio.cpp.o

olcPGEX_MiniAudio.i: olcPGEX_MiniAudio.cpp.i
.PHONY : olcPGEX_MiniAudio.i

# target to preprocess a source file
olcPGEX_MiniAudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPGEX_MiniAudio.cpp.i
.PHONY : olcPGEX_MiniAudio.cpp.i

olcPGEX_MiniAudio.s: olcPGEX_MiniAudio.cpp.s
.PHONY : olcPGEX_MiniAudio.s

# target to generate assembly for a file
olcPGEX_MiniAudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPGEX_MiniAudio.cpp.s
.PHONY : olcPGEX_MiniAudio.cpp.s

olcPixelGameEngine.o: olcPixelGameEngine.cpp.o
.PHONY : olcPixelGameEngine.o

# target to build an object file
olcPixelGameEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPixelGameEngine.cpp.o
.PHONY : olcPixelGameEngine.cpp.o

olcPixelGameEngine.i: olcPixelGameEngine.cpp.i
.PHONY : olcPixelGameEngine.i

# target to preprocess a source file
olcPixelGameEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPixelGameEngine.cpp.i
.PHONY : olcPixelGameEngine.cpp.i

olcPixelGameEngine.s: olcPixelGameEngine.cpp.s
.PHONY : olcPixelGameEngine.s

# target to generate assembly for a file
olcPixelGameEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/olcPixelGameEngine.cpp.s
.PHONY : olcPixelGameEngine.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shep.dir\build.make CMakeFiles/Shep.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... copy_data
	@echo ... Shep
	@echo ... CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.o
	@echo ... CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.i
	@echo ... CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.s
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
	@echo ... olcPGEX_MiniAudio.o
	@echo ... olcPGEX_MiniAudio.i
	@echo ... olcPGEX_MiniAudio.s
	@echo ... olcPixelGameEngine.o
	@echo ... olcPixelGameEngine.i
	@echo ... olcPixelGameEngine.s
	@echo ... util.o
	@echo ... util.i
	@echo ... util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

